version: "3.7"

services:
  case:
      build:
          context: ..
          dockerfile: docker/Dockerfile
      ports:
          - "8080:8080"
      environment:
        SPRING_PROFILES_ACTIVE: prod
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
          - postgres-case
          - pgadmin-case
      networks:
          - case-network

  postgres-case:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata-staging:/var/lib/postgresql/data
    networks:
      - case-network

  pgadmin-case:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmindata-staging:/var/lib/pgadmin/data
    depends_on:
      - postgres-case
    networks:
      - case-network

networks:
  case-network:
    driver: bridge

volumes:
  pgdata-staging:
    driver: local
  pgadmindata-staging:
    driver: local
